#!/usr/bin/env bash
function barebones() {

    set -e

    # 0. The project name
    project=$1

    if [[ -z "$project" ]]; then
        echo "Please provide a project name, for example 'barebones newsite'" 1>&2
        exit 1
    fi

    echo "Downloading the latest version of WordPress into the current folder..." 1>&2

    # 1. Download latest version of WordPress into current folder
    wget https://wordpress.org/latest.tar.gz
    tar -xvzf latest.tar.gz

    # 2. Rename directory to given project name
    mv wordpress $project
    rm latest.tar.gz
    cd $project

    # 3. Remove unnecessary files
    rm license.txt readme.html

    # 4. Create .gitignore file
    echo '.DS_Store
[Tt]humbs.db
.Trashes
.log
.env.php
sitemap.xml
wp-content/backup
wp-content/cache
wp-content/upgrade
wp-content/uploads
wp-content/blogs.dir
wp-content/backup-db
wp-content/advanced-cache.php
wp-content/wp-cache-config.php
wp-content/themes/*/.sass-cache
wp-content/themes/*/node_modules' > .gitignore

    # 5. Plugins
    ## 5.1. Remove unnecessary plugins
    cd wp-content/plugins
    rm -rf hello.php

    echo "Downloading useful plugins..." 1>&2

    ## 5.2. Download useful plugins
    wget https://downloads.wordpress.org/plugin/regenerate-thumbnails.zip
    wget https://downloads.wordpress.org/plugin/simple-history.zip
    wget https://downloads.wordpress.org/plugin/wordpress-seo.zip
    wget https://downloads.wordpress.org/plugin/classic-editor.zip

    tar -xvzf regenerate-thumbnails.zip
    tar -xvzf simple-history.zip
    tar -xvzf wordpress-seo.zip
    tar -xvzf classic-editor.zip
    rm -rf *.zip */.git

    # 6. Themes
    ## 6.1. Remove unnecessary themes
    cd ../themes
    rm -rf twentynineteen
    rm -rf twentytwenty

    echo "Cloning the barebones theme..." 1>&2

    ## 6.2. Clone barebones
    git clone https://github.com/benchmarkstudios/barebones
    mv barebones $project

    ## 6.3. Install barebones submodules
    cd $project
    git submodule init
    git submodule update

    ## 6.4. Remove unnecessary stuff
    rm -rf .git .gitattributes .gitignore .gitmodules README.md CHANGELOG.md assets/styles/vendor/simple-grid/.gitattributes assets/styles/vendor/simple-grid/README.md
    
    ## 6.5 Create ACF folder
    mkdir acf-json

    echo "Installing npm dependencies..." 1>&2

    # 7. Install all npm dependencies
    npm install

    echo "✅ New WordPress site '$project' has been installed" 1>&2

}

barebones $1
